In [182]:
import numpy as np


In [183]:
def calculate_x_n(a, b, c, d, n):
    #alpha = [0.0] * n
    #beta = [0.0] * n
    alpha = np.zeros(n)
    beta = np.zeros(n)    
    alpha[0] = -c[0] / b[0]
    beta[0] = d[0] / b[0]
    for i in range(1,n-1):
        #print(i)
        alpha[i] = -c[i] / (a[i-1]*alpha[i-1] + b[i])
        beta[i] = (d[i] - a[i-1]*beta[i-1]) / (a[i-1]*alpha[i-1] + b[i])
    x_n = (d[n-1] - a[n-2]*beta[n-2]) / (a[n-2]*alpha[n-2] + b[n-1])
    #print(alpha, beta)
    return x_n, alpha, beta

def calculate_x_vector(x_n, alpha, beta, n):
    x = [0.0] * (n-1)
    x.append(x_n)
    for i in range(n-2, -1, -1):
        x[i] = alpha[i]*x[i+1] + beta[i]
    return x

In [184]:
def func(x):
    return 2 * (1 - x)

def func1(x):
    return x**2 + np.exp(x)

In [185]:

n = 10
left_b = 0
right_b = 1
h = (right_b - left_b) / n

x = np.arange(left_b, right_b + h/2, h)
y = func(x)

y_verify = func1(x)

p = -1
q = 0
a_coefs = np.array([0.0] +  np.ones(n-2) - p * (h/2)*np.ones(n-2))
b_coefs = q * h**2 * np.ones(n-1) - 2*np.ones(n-1)
c_coefs = np.ones(n-2) + (h/2)*np.ones(n-2) * p
d_coefs = y[1:-1] * h**2

y0 = 1
yn = 1 + np.exp(1)

d_coefs[0] -= a_coefs[1] * y0
d_coefs[-1] -= c_coefs[0] * yn

print('a_coefs: ',a_coefs)
print('b_coefs: ',b_coefs)
print('c_coefs: ',c_coefs)
print('d_coefs: ',d_coefs)


a_coefs:  [1.05 1.05 1.05 1.05 1.05 1.05 1.05 1.05]
b_coefs:  [-2. -2. -2. -2. -2. -2. -2. -2. -2.]
c_coefs:  [0.95 0.95 0.95 0.95 0.95 0.95 0.95 0.95]
d_coefs:  [-1.032       0.016       0.014       0.012       0.01        0.008
  0.006       0.004      -3.53036774]


In [186]:
x_n, alpha, beta = calculate_x_n(a_coefs, b_coefs, c_coefs, d_coefs, n-1)
x = calculate_x_vector(x_n, alpha, beta, n-1)
print('Приближенное решение ', x)

Приближенное решение  [1.1151243048735462, 1.261314326049571, 1.4397348757704407, 1.651673378093507, 1.8985527753979483, 2.1819457934712783, 2.503590708183906, 2.8654087718136525, 3.269523473720214]


In [187]:
final_solution = np.concatenate(([y0], x, [yn]))
final_solution

array([1.        , 1.1151243 , 1.26131433, 1.43973488, 1.65167338,
       1.89855278, 2.18194579, 2.50359071, 2.86540877, 3.26952347,
       3.71828183])

In [188]:
delta = np.abs(y_verify - final_solution)
delta

array([0.00000000e+00, 4.66132021e-05, 8.84321106e-05, 1.23931806e-04,
       1.51319548e-04, 1.68495302e-04, 1.73006919e-04, 1.61999287e-04,
       1.32156679e-04, 7.96374367e-05, 0.00000000e+00])

In [189]:
for i in range(len(delta)):
    print("y=", y_verify[i], " | apr_sol=", final_solution[i], " | delta=", delta[i])

y= 1.0  | apr_sol= 1.0  | delta= 0.0
y= 1.1151709180756477  | apr_sol= 1.1151243048735462  | delta= 4.661320210153086e-05
y= 1.26140275816017  | apr_sol= 1.261314326049571  | delta= 8.843211059894607e-05
y= 1.4398588075760033  | apr_sol= 1.4397348757704407  | delta= 0.00012393180556258265
y= 1.6518246976412705  | apr_sol= 1.651673378093507  | delta= 0.00015131954776359535
y= 1.8987212707001282  | apr_sol= 1.8985527753979483  | delta= 0.00016849530217988296
y= 2.1821188003905094  | apr_sol= 2.1819457934712783  | delta= 0.00017300691923116673
y= 2.503752707470477  | apr_sol= 2.503590708183906  | delta= 0.00016199928657067986
y= 2.865540928492468  | apr_sol= 2.8654087718136525  | delta= 0.0001321566788154982
y= 3.26960311115695  | apr_sol= 3.269523473720214  | delta= 7.963743673577994e-05
y= 3.718281828459045  | apr_sol= 3.718281828459045  | delta= 0.0


In [190]:
A = 1
D_0 = A
D_1 = h
p = -1
q = 0

y_0 = np.zeros(n+1)
y_1 = np.zeros(n+1)
y_0[0] = 1
y_0[1] = 1
y_1[0] = 0
y_1[1] = h

In [191]:
for i in range(1, n):
    y_0[i+1] = (y[i] * h**2 + (2 - q * h**2) * y_0[i] - (1 - p * h/2) * y_0[i-1]) / (1 + p * h/2)
    y_1[i+1] = ((2 - q * h**2) * y_1[i] - (1 - p * h/2) * y_1[i-1]) / (1 + p * h/2)
y_0

array([1.        , 1.        , 1.01894737, 1.0567313 , 1.11322933,
       1.18830611, 1.28181201, 1.3935817 , 1.5234324 , 1.67116213,
       1.83654762])

In [192]:
B = 1 + np.exp(1)
C1 = (B - y_0[-1]) / y_1[-1]
y_final = y_0 + C1*y_1
y_final

array([1.        , 1.1151243 , 1.26131433, 1.43973488, 1.65167338,
       1.89855278, 2.18194579, 2.50359071, 2.86540877, 3.26952347,
       3.71828183])

In [193]:
delta = np.abs(y_verify - y_final)

In [194]:
for i in range(len(delta)):
    print("y=", y_verify[i], " | apr_sol=", y_final[i], " | delta=", delta[i])

y= 1.0  | apr_sol= 1.0  | delta= 0.0
y= 1.1151709180756477  | apr_sol= 1.1151243048735464  | delta= 4.6613202101308815e-05
y= 1.26140275816017  | apr_sol= 1.261314326049571  | delta= 8.843211059894607e-05
y= 1.4398588075760033  | apr_sol= 1.4397348757704405  | delta= 0.0001239318055628047
y= 1.6518246976412705  | apr_sol= 1.6516733780935065  | delta= 0.00015131954776403944
y= 1.8987212707001282  | apr_sol= 1.898552775397948  | delta= 0.000168495302180105
y= 2.1821188003905094  | apr_sol= 2.181945793471278  | delta= 0.00017300691923161082
y= 2.503752707470477  | apr_sol= 2.5035907081839053  | delta= 0.00016199928657156804
y= 2.865540928492468  | apr_sol= 2.8654087718136516  | delta= 0.00013215667881638637
y= 3.26960311115695  | apr_sol= 3.2695234737202137  | delta= 7.963743673622403e-05
y= 3.718281828459045  | apr_sol= 3.7182818284590446  | delta= 4.440892098500626e-16
