In [1]:
import numpy as np


In [2]:
def calculate_x_n(a, b, c, d, n):
    #alpha = [0.0] * n
    #beta = [0.0] * n
    alpha = np.zeros(n)
    beta = np.zeros(n)    
    alpha[0] = -c[0] / b[0]
    beta[0] = d[0] / b[0]
    for i in range(1,n-1):
        #print(i)
        alpha[i] = -c[i] / (a[i-1]*alpha[i-1] + b[i])
        beta[i] = (d[i] - a[i-1]*beta[i-1]) / (a[i-1]*alpha[i-1] + b[i])
    x_n = (d[n-1] - a[n-2]*beta[n-2]) / (a[n-2]*alpha[n-2] + b[n-1])
    #print(alpha, beta)
    return x_n, alpha, beta

def calculate_x_vector(x_n, alpha, beta, n):
    x = [0.0] * (n-1)
    x.append(x_n)
    for i in range(n-2, -1, -1):
        x[i] = alpha[i]*x[i+1] + beta[i]
    return x

In [3]:
def func(x):
    return np.exp(x)

In [4]:

n = 10
left_b = 0
right_b = 1
h = (right_b - left_b) / n

x = np.arange(left_b, right_b + h/2, h)
y = func(x)

a_coefs = np.array([0.0] +  np.ones(n-2) - (h/2)*np.ones(n-2))
b_coefs = -1 * h**2 * np.ones(n-1) - 2*np.ones(n-1)
c_coefs = np.ones(n-2) + (h/2)*np.ones(n-2)
d_coefs = y[1:-1] * h**2 

y0 = func(left_b)
yn = func(right_b)

d_coefs[0] -= a_coefs[1] * y0
d_coefs[-1] -= c_coefs[0] * yn

print('a_coefs: ',a_coefs)
print('b_coefs: ',b_coefs)
print('c_coefs: ',c_coefs)
print('d_coefs: ',d_coefs)


a_coefs:  [0.95 0.95 0.95 0.95 0.95 0.95 0.95 0.95]
b_coefs:  [-2.01 -2.01 -2.01 -2.01 -2.01 -2.01 -2.01 -2.01 -2.01]
c_coefs:  [1.05 1.05 1.05 1.05 1.05 1.05 1.05 1.05]
d_coefs:  [-0.93894829  0.01221403  0.01349859  0.01491825  0.01648721  0.01822119
  0.02013753  0.02225541 -2.82959989]


In [5]:
x_n, alpha, beta = calculate_x_n(a_coefs, b_coefs, c_coefs, d_coefs, n-1)
x = calculate_x_vector(x_n, alpha, beta, n-1)
print('Приближенное решение ', x)

Приближенное решение  [1.1053447081380232, 1.2217091167030314, 1.3502589327843548, 1.4922813162899364, 1.6491978157848073, 1.8225786399609751, 2.014158408885617, 2.225853543782731, 2.4597814703303595]


In [6]:
final_solution = np.concatenate(([y0], x, [yn]))
final_solution

array([1.        , 1.10534471, 1.22170912, 1.35025893, 1.49228132,
       1.64919782, 1.82257864, 2.01415841, 2.22585354, 2.45978147,
       2.71828183])

In [7]:
delta = np.abs(y - final_solution)
delta

array([0.        , 0.00017379, 0.00030636, 0.00040013, 0.00045662,
       0.00047655, 0.00045984, 0.0004057 , 0.00031262, 0.00017836,
       0.        ])

In [8]:
for i in range(len(delta)):
    print("y=", y[i], " | apr_sol=", final_solution[i], " | delta=", delta[i])

y= 1.0  | apr_sol= 1.0  | delta= 0.0
y= 1.1051709180756477  | apr_sol= 1.1053447081380232  | delta= 0.00017379006237550065
y= 1.2214027581601699  | apr_sol= 1.2217091167030314  | delta= 0.0003063585428615401
y= 1.3498588075760032  | apr_sol= 1.3502589327843548  | delta= 0.00040012520835164267
y= 1.4918246976412703  | apr_sol= 1.4922813162899364  | delta= 0.00045661864866608504
y= 1.6487212707001282  | apr_sol= 1.6491978157848073  | delta= 0.00047654508467909196
y= 1.822118800390509  | apr_sol= 1.8225786399609751  | delta= 0.0004598395704660252
y= 2.0137527074704766  | apr_sol= 2.014158408885617  | delta= 0.0004057014151404026
y= 2.225540928492468  | apr_sol= 2.225853543782731  | delta= 0.00031261529026327395
y= 2.45960311115695  | apr_sol= 2.4597814703303595  | delta= 0.00017835917340969232
y= 2.718281828459045  | apr_sol= 2.718281828459045  | delta= 0.0


In [20]:
A = 1
D_0 = A + 1e-1
D_1 = 1e-1
y_0 = np.concatenate(([A ,D_0], np.ones(n-1)))
y_1 = np.concatenate(([0, D_1], np.ones(n-1)))
y_0

array([1. , 1.1, 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ])

In [22]:
y_0[2:-1] = (y[1:-2] * h**2 + (2 + h**2)*y_0[1:-2] - (1 - h/2)*y_0[:-3]) / (1 + h/2)
y_0 = y_0[:-1]
y_0

array([1.        , 1.1       , 1.21147782, 1.33550899, 0.6983443 ,
       1.1292907 , 1.05040689, 1.05369543, 1.05732983, 1.06134647])

In [23]:
y_1[2:-1] = ((2 + h**2)*y_1[1:-2] - (1 - h/2)*y_1[:-3]) / (1 + h/2)
y_1 = y_1[:-1]
y_1

array([0.        , 0.1       , 0.19142857, 1.82380952, 1.00952381,
       1.00952381, 1.00952381, 1.00952381, 1.00952381, 1.00952381])

In [25]:
B = 1
C1 = (B - y_0[-1]) / y_1[-1]
y_final = y_0 + C1*y_1
y_final

array([1.        , 1.09392323, 1.19984514, 1.22468023, 0.63699783,
       1.06794423, 0.98906042, 0.99234896, 0.99598336, 1.        ])