In [1]:
import numpy as np

In [2]:
# from decimal import Decimal, getcontext
# getcontext().prec = 80

In [3]:
dim = 4

a_coeffs = np.array([0.0] + [1.0] * (dim - 1), dtype=np.longdouble)
b_coeffs = np.array([4.0] * dim, dtype=np.longdouble)
c_coeffs = np.array([1.0] * (dim - 1), dtype=np.longdouble)

d_coeffs = np.array([5.0, 6.0, 6.0, 5.0], dtype=np.longdouble)

In [4]:
# dim = 4

# a_coeffs = [Decimal(0.)] + [Decimal(1.)] * (dim - 1)
# b_coeffs = [Decimal(4.)] * dim
# c_coeffs = [Decimal(1.)] * (dim - 1)

# d_coeffs = [Decimal(5.), Decimal(6.), Decimal(6.), Decimal(5.)]

In [5]:
def solve_eq():
    alphas, betas = np.zeros(dim, dtype=np.float16), np.zeros(dim, dtype=np.float16)

    for i in range(dim-1):
        alphas[i+1] = -c_coeffs[i]/(a_coeffs[i] * alphas[i] + b_coeffs[i])
        betas[i+1] = (d_coeffs[i] - a_coeffs[i] * betas[i]) / (a_coeffs[i] * alphas[i] + b_coeffs[i])
    
    x = np.zeros(dim, dtype=np.longdouble)
    x[-1] = (d_coeffs[-1] - a_coeffs[-1] * betas[-1]) / (a_coeffs[-1] * alphas[-1] + b_coeffs[-1])

    for i in range(dim-1, 0, -1):
        x[i-1] = alphas[i] * x[i] + betas[i]

    return alphas, betas, x

In [6]:
# def solve_eq():
#     alphas, betas = [Decimal(0.01)] * dim, [Decimal(0.01)] * dim
#     alphas[1] = - c_coeffs[0] / b_coeffs[0]
#     betas[1] = d_coeffs[0] / b_coeffs[0]
#     for i in range(1, dim-1):
#         alphas[i+1] = -c_coeffs[i]/(a_coeffs[i] * alphas[i] + b_coeffs[i])
#         betas[i+1] = (d_coeffs[i] - a_coeffs[i] * betas[i]) / (a_coeffs[i] * alphas[i] + b_coeffs[i])
#         print(i, type(alphas[i+1]), type(betas[i+1]))
    
#     x = [Decimal(0.01)] * dim
#     x[-1] = (d_coeffs[-1] - a_coeffs[-1] * betas[-1]) / (a_coeffs[-1] * alphas[-1] + b_coeffs[-1])

#     for i in range(dim-1, 0, -1):
#         x[i-1] = alphas[i] * x[i] + betas[i]

#     return alphas, betas, x

In [7]:
solution = solve_eq()

In [8]:
solution

(array([ 0.        , -0.25      , -0.26666667, -0.26785714], dtype=float128),
 array([0.        , 1.25      , 1.26666667, 1.26785714], dtype=float128),
 array([1., 1., 1., 1.], dtype=float128))

In [9]:
A = np.array([[4, 1, 0, 0],
              [1, 4, 1, 0],
              [0, 1, 4, 1],
              [0, 0, 1, 4]])

np.dot(np.linalg.inv(A), np.array([5, 6, 6, 5]))

array([1., 1., 1., 1.])

In [10]:
np.set_printoptions(precision=25)

In [11]:
type(np.longdouble(1000000000000000000000001) / np.longdouble(1000000000000000000000000))

numpy.float128